// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package inventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InventoryIntegrationServiceClient is the client API for InventoryIntegrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryIntegrationServiceClient interface {
	// ListInventory returns what Zentail currently believes about the SKUs
	// stocked in the caller's warehouses.
	//
	// Two uses. It scopes a sweep — report only these SKUs rather than your whole
	// catalog. And it lets a caller send only genuine differences, which on a
	// large catalog is the difference between a viable poll loop and a pointless
	// one.
	ListInventory(ctx context.Context, in *ListInventoryRequest, opts ...grpc.CallOption) (*ListInventoryResponse, error)
	// UpdateInventory sets absolute on-hand quantities.
	//
	// Idempotent and order-insensitive: replaying a call changes nothing, and an
	// update whose observed_ts predates what Zentail already holds is discarded
	// and reported as stale rather than applied. A slow retry overtaking a newer
	// reading cannot roll the count backwards.
	UpdateInventory(ctx context.Context, in *UpdateInventoryRequest, opts ...grpc.CallOption) (*UpdateInventoryResponse, error)
	// IntegrationStatus returns diagnostic checks for the caller's integration —
	// whether warehouses are bound to it, when stock was last reported, and
	// whether Zentail considers that reading stale.
	//
	// An inventory integration fails quietly: nothing errors when a poll loop
	// stops, the numbers simply age. This is how that surfaces.
	IntegrationStatus(ctx context.Context, in *IntegrationStatusRequest, opts ...grpc.CallOption) (*IntegrationStatusResponse, error)
}

type inventoryIntegrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryIntegrationServiceClient(cc grpc.ClientConnInterface) InventoryIntegrationServiceClient {
	return &inventoryIntegrationServiceClient{cc}
}

func (c *inventoryIntegrationServiceClient) ListInventory(ctx context.Context, in *ListInventoryRequest, opts ...grpc.CallOption) (*ListInventoryResponse, error) {
	out := new(ListInventoryResponse)
	err := c.cc.Invoke(ctx, "/inventory_api.InventoryIntegrationService/ListInventory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryIntegrationServiceClient) UpdateInventory(ctx context.Context, in *UpdateInventoryRequest, opts ...grpc.CallOption) (*UpdateInventoryResponse, error) {
	out := new(UpdateInventoryResponse)
	err := c.cc.Invoke(ctx, "/inventory_api.InventoryIntegrationService/UpdateInventory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryIntegrationServiceClient) IntegrationStatus(ctx context.Context, in *IntegrationStatusRequest, opts ...grpc.CallOption) (*IntegrationStatusResponse, error) {
	out := new(IntegrationStatusResponse)
	err := c.cc.Invoke(ctx, "/inventory_api.InventoryIntegrationService/IntegrationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryIntegrationServiceServer is the server API for InventoryIntegrationService service.
// All implementations should embed UnimplementedInventoryIntegrationServiceServer
// for forward compatibility
type InventoryIntegrationServiceServer interface {
	// ListInventory returns what Zentail currently believes about the SKUs
	// stocked in the caller's warehouses.
	//
	// Two uses. It scopes a sweep — report only these SKUs rather than your whole
	// catalog. And it lets a caller send only genuine differences, which on a
	// large catalog is the difference between a viable poll loop and a pointless
	// one.
	ListInventory(context.Context, *ListInventoryRequest) (*ListInventoryResponse, error)
	// UpdateInventory sets absolute on-hand quantities.
	//
	// Idempotent and order-insensitive: replaying a call changes nothing, and an
	// update whose observed_ts predates what Zentail already holds is discarded
	// and reported as stale rather than applied. A slow retry overtaking a newer
	// reading cannot roll the count backwards.
	UpdateInventory(context.Context, *UpdateInventoryRequest) (*UpdateInventoryResponse, error)
	// IntegrationStatus returns diagnostic checks for the caller's integration —
	// whether warehouses are bound to it, when stock was last reported, and
	// whether Zentail considers that reading stale.
	//
	// An inventory integration fails quietly: nothing errors when a poll loop
	// stops, the numbers simply age. This is how that surfaces.
	IntegrationStatus(context.Context, *IntegrationStatusRequest) (*IntegrationStatusResponse, error)
}

// UnimplementedInventoryIntegrationServiceServer should be embedded to have forward compatible implementations.
type UnimplementedInventoryIntegrationServiceServer struct {
}

func (UnimplementedInventoryIntegrationServiceServer) ListInventory(context.Context, *ListInventoryRequest) (*ListInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInventory not implemented")
}
func (UnimplementedInventoryIntegrationServiceServer) UpdateInventory(context.Context, *UpdateInventoryRequest) (*UpdateInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInventory not implemented")
}
func (UnimplementedInventoryIntegrationServiceServer) IntegrationStatus(context.Context, *IntegrationStatusRequest) (*IntegrationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IntegrationStatus not implemented")
}

// UnsafeInventoryIntegrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryIntegrationServiceServer will
// result in compilation errors.
type UnsafeInventoryIntegrationServiceServer interface {
	mustEmbedUnimplementedInventoryIntegrationServiceServer()
}

func RegisterInventoryIntegrationServiceServer(s grpc.ServiceRegistrar, srv InventoryIntegrationServiceServer) {
	s.RegisterService(&InventoryIntegrationService_ServiceDesc, srv)
}

func _InventoryIntegrationService_ListInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryIntegrationServiceServer).ListInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory_api.InventoryIntegrationService/ListInventory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryIntegrationServiceServer).ListInventory(ctx, req.(*ListInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryIntegrationService_UpdateInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryIntegrationServiceServer).UpdateInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory_api.InventoryIntegrationService/UpdateInventory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryIntegrationServiceServer).UpdateInventory(ctx, req.(*UpdateInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryIntegrationService_IntegrationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryIntegrationServiceServer).IntegrationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory_api.InventoryIntegrationService/IntegrationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryIntegrationServiceServer).IntegrationStatus(ctx, req.(*IntegrationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryIntegrationService_ServiceDesc is the grpc.ServiceDesc for InventoryIntegrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryIntegrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory_api.InventoryIntegrationService",
	HandlerType: (*InventoryIntegrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInventory",
			Handler:    _InventoryIntegrationService_ListInventory_Handler,
		},
		{
			MethodName: "UpdateInventory",
			Handler:    _InventoryIntegrationService_UpdateInventory_Handler,
		},
		{
			MethodName: "IntegrationStatus",
			Handler:    _InventoryIntegrationService_IntegrationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory_api/inventory/service.proto",
}
